export default {
  applied_rule_ids: "40",
  base_currency_code: "USD",
  base_discount_amount: -1.7,
  base_grand_total: 25.3,
  base_discount_tax_compensation_amount: 0,
  base_shipping_amount: 10,
  base_shipping_incl_tax: 10,
  base_shipping_tax_amount: 0,
  base_subtotal: 17,
  base_subtotal_incl_tax: 17,
  base_tax_amount: 0,
  base_total_due: 25.3,
  base_to_global_rate: 1,
  base_to_order_rate: 1,
  billing_address_id: 2,
  created_at: "2020-09-05 00:14:02",
  customer_email: "order_12@example.com",
  customer_group_id: 0,
  customer_is_guest: 1,
  customer_note_notify: 1,
  discount_amount: -1.7,
  email_sent: 1,
  entity_id: 12,
  global_currency_code: "USD",
  grand_total: 25.3,
  discount_tax_compensation_amount: 0,
  increment_id: "400000012",
  is_virtual: 0,
  order_currency_code: "USD",
  protect_code: "272ecb",
  quote_id: 12,
  remote_ip: "127.0.0.1",
  shipping_amount: 10,
  shipping_description: "Flat Rate - Fixed",
  shipping_discount_tax_compensation_amount: 0,
  shipping_incl_tax: 10,
  shipping_tax_amount: 0,
  state: "new",
  status: "pending",
  store_currency_code: "USD",
  store_id: 4,
  store_name:
    "Website 4\nStore Group 4 - website_id_4\nStore view 4 - website_id_4 - group_id_4",
  store_to_base_rate: 0,
  store_to_order_rate: 0,
  subtotal: 17,
  subtotal_incl_tax: 17,
  tax_amount: 0,
  total_due: 25.3,
  total_item_count: 2,
  total_qty_ordered: 2,
  updated_at: "2020-09-05 00:14:02",
  weight: 2,
  items: [
    {
      amount_refunded: 0,
      applied_rule_ids: "40",
      base_amount_refunded: 0,
      base_discount_amount: 0.85,
      base_discount_invoiced: 0,
      base_discount_tax_compensation_amount: 0,
      base_original_price: 10,
      base_price: 8.5,
      base_price_incl_tax: 8.5,
      base_row_invoiced: 0,
      base_row_total: 7.65,
      base_row_total_incl_tax: 7.65,
      base_tax_amount: 0,
      base_tax_invoiced: 0,
      created_at: "2020-09-05 00:14:02",
      discount_amount: 0.85,
      discount_invoiced: 0,
      discount_percent: 10,
      free_shipping: 0,
      discount_tax_compensation_amount: 0,
      is_qty_decimal: 0,
      is_virtual: 0,
      item_id: 23,
      name: "Simple Product 1",
      no_discount: 0,
      order_id: 12,
      original_price: 10,
      parent_item_id: 0,
      price: 8.5,
      price_incl_tax: 8.5,
      product_id: 1,
      product_type: "simple",
      qty_canceled: 0,
      qty_invoiced: 0,
      qty_ordered: 1,
      qty_refunded: 0,
      qty_shipped: 0,
      quote_item_id: 23,
      row_invoiced: 0,
      row_total: 7.65,
      row_total_incl_tax: 7.65,
      row_weight: 1,
      sku: "product_dynamic_1",
      store_id: 4,
      tax_amount: 0,
      tax_invoiced: 0,
      tax_percent: 0,
      updated_at: "0000-00-00 00:00:00",
      weight: 1,
    },
    {
      amount_refunded: 0,
      applied_rule_ids: "40",
      base_amount_refunded: 0,
      base_discount_amount: 0.85,
      base_discount_invoiced: 0,
      base_discount_tax_compensation_amount: 0,
      base_original_price: 10,
      base_price: 8.5,
      base_price_incl_tax: 8.5,
      base_row_invoiced: 0,
      base_row_total: 7.65,
      base_row_total_incl_tax: 7.65,
      base_tax_amount: 0,
      base_tax_invoiced: 0,
      created_at: "2020-09-05 00:14:02",
      discount_amount: 0.85,
      discount_invoiced: 0,
      discount_percent: 10,
      free_shipping: 0,
      discount_tax_compensation_amount: 0,
      is_qty_decimal: 0,
      is_virtual: 0,
      item_id: 24,
      name: "Simple Product 2",
      no_discount: 0,
      order_id: 12,
      original_price: 10,
      parent_item_id: 0,
      price: 8.5,
      price_incl_tax: 8.5,
      product_id: 2,
      product_type: "simple",
      qty_canceled: 0,
      qty_invoiced: 0,
      qty_ordered: 1,
      qty_refunded: 0,
      qty_shipped: 0,
      quote_item_id: 24,
      row_invoiced: 0,
      row_total: 7.65,
      row_total_incl_tax: 7.65,
      row_weight: 1,
      sku: "product_dynamic_2",
      store_id: 4,
      tax_amount: 0,
      tax_invoiced: 0,
      tax_percent: 0,
      updated_at: "0000-00-00 00:00:00",
      weight: 1,
    },
  ],
  billing_address: {
    address_type: "billing",
    city: "city",
    company: "Company",
    country_id: "US",
    email: "order_12@example.com",
    entity_id: 24,
    firstname: "First Name",
    lastname: "Last Name",
    parent_id: 12,
    postcode: "11111",
    region: "Alabama",
    region_code: "AL",
    region_id: 1,
    street: ["Address"],
    telephone: "911",
  },
  payment: {
    account_status: null,
    additional_information: ["Check / Money order"],
    amount_ordered: 25.3,
    base_amount_ordered: 25.3,
    base_shipping_amount: 10,
    cc_last4: null,
    cc_ss_start_month: "0",
    cc_ss_start_year: "0",
    entity_id: 12,
    method: "checkmo",
    parent_id: 12,
    shipping_amount: 10,
  },
  status_histories: [
    {
      comment: null,
      created_at: "2020-09-05 00:14:02",
      entity_id: 12,
      entity_name: "order",
      is_customer_notified: 1,
      is_visible_on_front: 0,
      parent_id: 12,
      status: "pending",
    },
  ],
  extension_attributes: {
    shipping_assignments: [
      {
        shipping: {
          address: {
            address_type: "shipping",
            city: "city",
            company: "Company",
            country_id: "US",
            email: "order_12@example.com",
            entity_id: 23,
            firstname: "First Name",
            lastname: "Last Name",
            parent_id: 12,
            postcode: "11111",
            region: "Alabama",
            region_code: "AL",
            region_id: 1,
            street: ["Address"],
            telephone: "911",
          },
          method: "flatrate_flatrate",
          total: {
            base_shipping_amount: 10,
            base_shipping_incl_tax: 10,
            base_shipping_tax_amount: 0,
            shipping_amount: 10,
            shipping_discount_tax_compensation_amount: 0,
            shipping_incl_tax: 10,
            shipping_tax_amount: 0,
          },
        },
        items: [
          {
            amount_refunded: 0,
            applied_rule_ids: "40",
            base_amount_refunded: 0,
            base_discount_amount: 0.85,
            base_discount_invoiced: 0,
            base_discount_tax_compensation_amount: 0,
            base_original_price: 10,
            base_price: 8.5,
            base_price_incl_tax: 8.5,
            base_row_invoiced: 0,
            base_row_total: 7.65,
            base_row_total_incl_tax: 7.65,
            base_tax_amount: 0,
            base_tax_invoiced: 0,
            created_at: "2020-09-05 00:14:02",
            discount_amount: 0.85,
            discount_invoiced: 0,
            discount_percent: 10,
            free_shipping: 0,
            discount_tax_compensation_amount: 0,
            is_qty_decimal: 0,
            is_virtual: 0,
            item_id: 23,
            name: "Simple Product 1",
            no_discount: 0,
            order_id: 12,
            original_price: 10,
            parent_item_id: 0,
            price: 8.5,
            price_incl_tax: 8.5,
            product_id: 1,
            product_type: "simple",
            qty_canceled: 0,
            qty_invoiced: 0,
            qty_ordered: 1,
            qty_refunded: 0,
            qty_shipped: 0,
            quote_item_id: 23,
            row_invoiced: 0,
            row_total: 7.65,
            row_total_incl_tax: 7.65,
            row_weight: 1,
            sku: "product_dynamic_1",
            store_id: 4,
            tax_amount: 0,
            tax_invoiced: 0,
            tax_percent: 0,
            updated_at: "0000-00-00 00:00:00",
            weight: 1,
          },
          {
            amount_refunded: 0,
            applied_rule_ids: "40",
            base_amount_refunded: 0,
            base_discount_amount: 0.85,
            base_discount_invoiced: 0,
            base_discount_tax_compensation_amount: 0,
            base_original_price: 10,
            base_price: 8.5,
            base_price_incl_tax: 8.5,
            base_row_invoiced: 0,
            base_row_total: 7.65,
            base_row_total_incl_tax: 7.65,
            base_tax_amount: 0,
            base_tax_invoiced: 0,
            created_at: "2020-09-05 00:14:02",
            discount_amount: 0.85,
            discount_invoiced: 0,
            discount_percent: 10,
            free_shipping: 0,
            discount_tax_compensation_amount: 0,
            is_qty_decimal: 0,
            is_virtual: 0,
            item_id: 24,
            name: "Simple Product 2",
            no_discount: 0,
            order_id: 12,
            original_price: 10,
            parent_item_id: 0,
            price: 8.5,
            price_incl_tax: 8.5,
            product_id: 2,
            product_type: "simple",
            qty_canceled: 0,
            qty_invoiced: 0,
            qty_ordered: 1,
            qty_refunded: 0,
            qty_shipped: 0,
            quote_item_id: 24,
            row_invoiced: 0,
            row_total: 7.65,
            row_total_incl_tax: 7.65,
            row_weight: 1,
            sku: "product_dynamic_2",
            store_id: 4,
            tax_amount: 0,
            tax_invoiced: 0,
            tax_percent: 0,
            updated_at: "0000-00-00 00:00:00",
            weight: 1,
          },
        ],
      },
    ],
    payment_additional_info: [
      {
        key: "method_title",
        value: "Check / Money order",
      },
    ],
    applied_taxes: [],
    item_applied_taxes: [],
  },
};
